# Generated by Django 5.0.6 on 2024-05-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application_object.catalog')),
            ],
            bases=('application_object.catalog',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application_object.catalog')),
            ],
            bases=('application_object.catalog',),
        ),
        migrations.CreateModel(
            name='NomenclatureTag',
            fields=[
                ('catalog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application_object.catalog')),
                ('rfid_tag', models.CharField(max_length=250)),
                ('nomenclature_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nomenclature')),
            ],
            bases=('application_object.catalog',),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='unit_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit'),
        ),
    ]
